---
- hosts: all
  become: true

  tasks:
    - name: Service File installed
      copy:
        src: get_gesetz.service
        dest: /etc/systemd/system
        owner: root
        group: root
      notify:
        - Service got updated

    - name: Service Script installed
      copy:
        src: get_gesetz.sh
        dest: /home/vagrant/

    - name: nginx installed
      apt: 
        name: nginx
        state: latest
      notify:
        - nginx is running

    - name: LawExtractor installed
      copy:
        src: LawExtractor.py
        dest: /home/vagrant/

    - name: nginx config loaded
      copy:
        src: default
        dest: /etc/nginx/sites-available
      notify:
        - nginx restarted

    - name: React deployed
      copy:
        src: web_app/build
        dest: /var/www/html/

  handlers:
    - name: Service got updated
      service:
        name: get_gesetz
        state: started
        enabled: yes

    - name: nginx is running
      service:
        name: nginx
        state: started
        enabled: yes
    
    - name: nginx restarted
      service:
        name: nginx
        state: restarted
        
